#pragma once

#define ATKINSON_HYPERLEGIBLE_8_FONT_ID (0)
#define ATKINSON_HYPERLEGIBLE_10_FONT_ID (1)
#define ATKINSON_HYPERLEGIBLE_12_FONT_ID (2)
#define ATKINSON_HYPERLEGIBLE_14_FONT_ID (3)
#define ATKINSON_HYPERLEGIBLE_16_FONT_ID (4)
#define ATKINSON_HYPERLEGIBLE_18_FONT_ID (5)
