/**
 * @file LibraryIndex.cpp
 * @brief Reader for the on-disk library.idx generated by LibraryIndexer.
 */

#include "LibraryIndex.h"

#include <SDCardManager.h>

#include <algorithm>
#include <cctype>
#include <cstring>

namespace {

constexpr const char* kIndexPath = "/.metadata/library/library.idx";
constexpr uint8_t kLegacyVersion = 1;
constexpr uint8_t kCurrentVersion = 2;

std::string lower(std::string value) {
  std::transform(value.begin(), value.end(), value.begin(), [](const unsigned char c) {
    return static_cast<char>(std::tolower(c));
  });
  return value;
}

std::string folderName(const std::string& path) {
  if (path.empty() || path == "/") {
    return "Root";
  }
  const size_t slash = path.find_last_of('/');
  return slash == std::string::npos ? path : path.substr(slash + 1);
}

bool matches(const std::string& needle, const LibraryIndex::Book& book) {
  if (needle.empty()) {
    return true;
  }
  return lower(book.title).find(needle) != std::string::npos ||
         lower(book.folder).find(needle) != std::string::npos ||
         lower(book.path).find(needle) != std::string::npos;
}

bool readHeader(FsFile& file, uint8_t& version) {
  char magic[4] = {};
  return file.read(magic, sizeof(magic)) == sizeof(magic) && std::memcmp(magic, "LIBX", sizeof(magic)) == 0 &&
         file.read(&version, sizeof(version)) == sizeof(version) &&
         (version == kLegacyVersion || version == kCurrentVersion);
}

}  // namespace

bool LibraryIndex::hasIndex() { return SdMan.exists(kIndexPath); }

bool LibraryIndex::deleteIndex() { return !hasIndex() || SdMan.remove(kIndexPath); }

bool LibraryIndex::readText(FsFile& file, const size_t length, std::string& value) {
  value.clear();
  if (length == 0) {
    return true;
  }
  std::vector<char> buffer(length + 1, '\0');
  if (file.read(buffer.data(), length) != length) {
    return false;
  }
  value.assign(buffer.data(), length);
  return true;
}

bool LibraryIndex::readEntry(FsFile& file, const uint8_t marker, const uint8_t version, Book& book, bool& found) {
  found = false;
  if (marker == 0x01) {
    book = {};
    uint16_t pathLength = 0;
    uint8_t nameLength = 0;
    uint8_t titleLength = 0;
    uint8_t folderLength = 0;
    if (file.read(&pathLength, sizeof(pathLength)) != sizeof(pathLength) ||
        !readText(file, pathLength, book.path) || file.read(&nameLength, sizeof(nameLength)) != sizeof(nameLength) ||
        !file.seek(file.position() + nameLength) || file.read(&titleLength, sizeof(titleLength)) != sizeof(titleLength) ||
        !readText(file, titleLength, book.title) || file.read(&folderLength, sizeof(folderLength)) != sizeof(folderLength) ||
        !readText(file, folderLength, book.folder)) {
      return false;
    }
    book.type = Book::Type::BOOK;
    found = true;
    return true;
  }

  if (marker == 0xFF) {
    uint16_t pathLength = 0;
    uint16_t entryCount = 0;
    uint16_t bookCount = 0;
    uint16_t folderCount = 0;
    std::string path;
    if (file.read(&pathLength, sizeof(pathLength)) != sizeof(pathLength) ||
        !readText(file, pathLength, path) || file.read(&entryCount, sizeof(entryCount)) != sizeof(entryCount)) {
      return false;
    }
    if (version >= kCurrentVersion &&
        (file.read(&bookCount, sizeof(bookCount)) != sizeof(bookCount) ||
         file.read(&folderCount, sizeof(folderCount)) != sizeof(folderCount))) {
      return false;
    }
    if (path == "/" || entryCount == 0) {
      return true;
    }
    book = {};
    book.type = Book::Type::FOLDER;
    book.path = path;
    book.title = folderName(path);
    const size_t slash = path.find_last_of('/');
    book.folder = slash <= 0 ? "Library" : path.substr(0, slash);
    book.bookCount = bookCount;
    book.folderCount = folderCount;
    book.hasMetadata = version >= kCurrentVersion;
    found = true;
    return true;
  }

  return marker == 0xFE;
}

bool LibraryIndex::search(const std::string& query, std::vector<Book>& results, const size_t limit) {
  results.clear();
  if (limit == 0 || !hasIndex()) {
    return false;
  }

  FsFile file = SdMan.open(kIndexPath, O_READ);
  if (!file) {
    return false;
  }
  uint8_t version = 0;
  if (!readHeader(file, version)) {
    file.close();
    return false;
  }

  // Search is used by the on-device search page with a small result limit. Keep
  // only the sorted top results while scanning instead of accumulating the
  // entire library and trimming it afterward. The unbounded path remains
  // available for the library browser and maintenance operations.
  const std::string needle = lower(query);
  if (limit != all) {
    results.reserve(limit);
  }

  while (file.available()) {
    uint8_t marker = 0;
    if (file.read(&marker, sizeof(marker)) != sizeof(marker)) {
      file.close();
      results.clear();
      return false;
    }
    Book book;
    bool found = false;
    if (!readEntry(file, marker, version, book, found)) {
      file.close();
      results.clear();
      return false;
    }
    if (found && matches(needle, book)) {
      if (limit == all) {
        results.push_back(std::move(book));
      } else {
        const auto position = std::lower_bound(
            results.begin(), results.end(), book,
            [](const Book& left, const Book& right) { return lower(left.title) < lower(right.title); });
        results.insert(position, std::move(book));
        if (results.size() > limit) {
          results.pop_back();
        }
      }
    }
  }
  file.close();

  if (limit == all) {
    std::sort(results.begin(), results.end(), [](const Book& left, const Book& right) {
      return lower(left.title) < lower(right.title);
    });
  }
  return true;
}
