#pragma once

/**
 * @file LibraryIndex.h
 * @brief Reader for the on-disk library.idx generated by LibraryIndexer.
 */

#include <cstdint>
#include <limits>
#include <string>
#include <vector>

/** Lightweight indexed library entries shared by the new Library page views. */
class LibraryIndex final {
 public:
  static constexpr size_t all = std::numeric_limits<size_t>::max();

  struct Book {
    enum class Type { BOOK, FOLDER };

    Type type = Type::BOOK;
    std::string path;
    std::string title;
    std::string folder;
    std::string author;
    uint16_t bookCount = 0;
    uint16_t folderCount = 0;
    bool hasMetadata = false;
  };

  static bool hasIndex();
  static bool deleteIndex();
  static bool search(const std::string& query, std::vector<Book>& results, size_t limit = 24);

 private:
  static bool readText(class FsFile& file, size_t length, std::string& value);
  static bool readEntry(class FsFile& file, uint8_t marker, uint8_t version, Book& book, bool& found);
};
