#pragma once

#include <system/font/system_font_8_regular.h>
#include <system/font/system_font_10_regular.h>
#include <system/font/system_font_10_bold.h>
#include <system/font/system_font_10_bolditalic.h>
#include <system/font/system_font_10_italic.h>
#include <system/font/system_font_12_bold.h>
#include <system/font/system_font_12_bolditalic.h>
#include <system/font/system_font_12_italic.h>
#include <system/font/system_font_12_regular.h>
#include <system/font/system_font_14_bold.h>
#include <system/font/system_font_14_bolditalic.h>
#include <system/font/system_font_14_italic.h>
#include <system/font/system_font_14_regular.h>
#include <system/font/system_font_16_bold.h>
#include <system/font/system_font_16_bolditalic.h>
#include <system/font/system_font_16_italic.h>
#include <system/font/system_font_16_regular.h>
#include <system/font/system_font_18_bold.h>
#include <system/font/system_font_18_bolditalic.h>
#include <system/font/system_font_18_italic.h>
#include <system/font/system_font_18_regular.h>
