#pragma once

#include <builtinFonts/bookerly_10_bold.h>
#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_10_bolditalic.h>
#include <builtinFonts/bookerly_12_bolditalic.h>
#include <builtinFonts/bookerly_10_italic.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_10_regular.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_bolditalic.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/atkinson_hyperlegible_8_regular.h>
#include <builtinFonts/atkinson_hyperlegible_10_regular.h>
#include <builtinFonts/atkinson_hyperlegible_10_bold.h>
#include <builtinFonts/atkinson_hyperlegible_10_bolditalic.h>
#include <builtinFonts/atkinson_hyperlegible_10_italic.h>
#include <builtinFonts/atkinson_hyperlegible_12_bold.h>
#include <builtinFonts/atkinson_hyperlegible_12_bolditalic.h>
#include <builtinFonts/atkinson_hyperlegible_12_italic.h>
#include <builtinFonts/atkinson_hyperlegible_12_regular.h>
#include <builtinFonts/atkinson_hyperlegible_14_bold.h>
#include <builtinFonts/atkinson_hyperlegible_14_bolditalic.h>
#include <builtinFonts/atkinson_hyperlegible_14_italic.h>
#include <builtinFonts/atkinson_hyperlegible_14_regular.h>
#include <builtinFonts/atkinson_hyperlegible_16_bold.h>
#include <builtinFonts/atkinson_hyperlegible_16_bolditalic.h>
#include <builtinFonts/atkinson_hyperlegible_16_italic.h>
#include <builtinFonts/atkinson_hyperlegible_16_regular.h>
#include <builtinFonts/atkinson_hyperlegible_18_bold.h>
#include <builtinFonts/atkinson_hyperlegible_18_bolditalic.h>
#include <builtinFonts/atkinson_hyperlegible_18_italic.h>
#include <builtinFonts/atkinson_hyperlegible_18_regular.h>
#include <builtinFonts/literata_10_regular.h>
#include <builtinFonts/literata_12_regular.h>
#include <builtinFonts/literata_14_regular.h>
#include <builtinFonts/literata_16_regular.h>
#include <builtinFonts/literata_18_regular.h>
#include <builtinFonts/literata_10_bold.h>
#include <builtinFonts/literata_12_bold.h>
#include <builtinFonts/literata_14_bold.h>
#include <builtinFonts/literata_16_bold.h>
#include <builtinFonts/literata_18_bold.h>
#include <builtinFonts/literata_10_italic.h>
#include <builtinFonts/literata_12_italic.h>
#include <builtinFonts/literata_14_italic.h>
#include <builtinFonts/literata_16_italic.h>
#include <builtinFonts/literata_18_italic.h>
#include <builtinFonts/literata_10_bolditalic.h>
#include <builtinFonts/literata_12_bolditalic.h>
#include <builtinFonts/literata_14_bolditalic.h>
#include <builtinFonts/literata_16_bolditalic.h>
#include <builtinFonts/literata_18_bolditalic.h>
