#!/usr/bin/env python3
"""Embed data/js/*.js into C++ PROGMEM headers (in firmware.bin; no SPIFFS for /js)."""

import os

REPO_ROOT = os.environ.get("PLATFORMIO_PROJECT_DIR", os.getcwd())

# (source under repo root, header under repo root, C array name, raw-string delimiter)
EMBEDS = [
    ("data/js/inx_font_pack.js", "src/network/html/InxFontPackJs.generated.h", "INX_FONT_PACK_JS", "INXFP"),
    ("data/js/jszip.min.js", "src/network/html/JsZipMinJs.generated.h", "JSZIP_MIN_JS", "INXJZ9"),
]


def write_header(js_path: str, out_path: str, array_name: str, delim: str) -> int:
    if not os.path.isfile(js_path):
        raise SystemExit(f"embed_js_firmware: missing {js_path}")

    with open(js_path, "r", encoding="utf-8") as f:
        body = f.read()

    close_seq = f"){delim}"
    if close_seq in body:
        raise SystemExit(f"embed_js_firmware: {js_path} contains forbidden sequence {close_seq!r}; change delim")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as h:
        h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
        h.write("#pragma once\n\n")
        h.write("#include <Arduino.h>\n\n")
        h.write(f'constexpr char {array_name}[] PROGMEM = R"{delim}(')
        h.write(body)
        h.write(f'){delim}";\n')

    n = len(body.encode("utf-8"))
    print(f"Generated: {out_path} ({n} bytes)")
    return n


def main() -> None:
    for rel_js, rel_out, array_name, delim in EMBEDS:
        js_path = os.path.join(REPO_ROOT, rel_js)
        out_path = os.path.join(REPO_ROOT, rel_out)
        write_header(js_path, out_path, array_name, delim)


if __name__ == "__main__":
    main()
